export default {
  GET_AUTHOR: "GET_AUTHOR",
  CHANGE_AUTHOR: "CHANGE_AUTHOR",
  SAVE_AUTHOR: "SAVE_AUTHOR",
  DELETE_AUTHOR: "DELETE_AUTHOR",
  CLEAR_AUTHOR: "CLEAR_AUTHOR",

  GET_AUTHOR_COURSES: "GET_AUTHOR_COURSES",
  CLEAR_AUTHOR_COURSES: "CLEAR_AUTHOR_COURSES"
};
